### ISSUE TITLE
Bluetooth headset isn't used when the headset is connected later than the application

### ISSUE THREAD

**Issue by paales** [eofster/Telephone#111]
When telephone is running and you connect your headset after that, it isn't automatically picked up (despite having configured it before).

If the headset disconnects and reconnects while the program is running, it doesn't work at all any more. It tries to output to the old headset or something. After restarting the application works again. This isn't so much a problem with and outgoing call, but it is a problem with an incoming call.

**Comment by koorb** [comment]
I am having this issue as well. Seems the headset disconnects, when a call comes in the application hangs if it answers there's no audio in or out via the headset or the computer.

I'm also running Yosemite

**Comment by zevlag** [comment]
Yes,  I think this used to work properly in older OS X versions.  But now, if an audio input / output device is connected after the application is launched, it can't be used.

**Comment by zevlag** [comment]
I would pay to have this bug fixed... Who wants to fix it?

**Comment by eofster** [comment]
I’ve just found and fixed a problem when audio devices connected when Telephone was already running could not be used by the app until it was restarted. The problem exists only in the recent versions of OS X. This might also affect the problem with bluetooth devices.

Related issue #143

**Comment by eofster** [comment]
Fixed in #143 and #145.
