### ISSUE TITLE
No sound for outgoing calls (no Fritz!box)

### ISSUE THREAD

**Issue by ThomasRo** [eofster/Telephone#115]
Hi there,

incoming calls are doing fine for me, but outgoing do not. During them, i cannot here the person i have called, though he is hearing me well. (There has been a simular issue with Frtz!Box users in the past, but i am not using Fritz!Box but an Asus router).

I did had the same problems with "Zoiper", and could fix it there by setting the "RTP Port" to a fix port (51600) and additionally i had to add a fix forwardingof this port to my Mac in the router configuration.

**Comment by muja** [comment]
I'm having the same issue. It kills the experience for me.

**Comment by eofster** [comment]
If the problem is still relevant, please write to the [support address](http://64characters.com/support/). Most likely this is a networking issue that will require gathering a debug log, which we probably don’t want to share here.
