### ISSUE TITLE
Mute sometimes does not mute

### ISSUE THREAD

**Issue by benrubson** [eofster/Telephone#118]
Hello,

I have found a bug with mute function.

During a call, mute microphone, you will then see "mic muted".
Then, hold the call and resume it, you will see "on hold" then "off hold".
Just after this, you will still see the message "mic muted", well, as expected.
However, mic is no more muted here !

Expected behavior here is to have mic still muted.

Thank you !

**Comment by benrubson** [comment]
As we do not have so many news from the developper, I tried to correct this issue myself.
So for those who have to courage to recompile Telephone to have their proper patched version, here is a workaround.

In Classes/Model/AKSIPUserAgent.m, in AKSIPCallMediaStateChanged method, at the end of dispatch_async, add :
if ([call isMicrophoneMuted]) {
pjsua_conf_disconnect(0, callInfo.conf_slot);
}

**Comment by eofster** [comment]
#181

**Comment by eofster** [comment]
Fixed in #181.

**Comment by benrubson** [comment]
:+1:
