### ISSUE TITLE
Cut window title to phone number only

### ISSUE THREAD

**Issue by benrubson** [eofster/Telephone#119]
Hello,

Could you please add an option (or do it by default) in order to cut the incoming call window title to the calling number only ?
For the moment, this title is like this : `<calling_number>@<trunk_ip>`
Title like this would be better / easier to read : `<calling_number>`

Same for outgoing call, only the `<called_number>`
(but seems to already be the case)

In addition, in the window title, a small arrow as a prefix to remember wether it is an incoming call (`↓`) or an outgoing call (`↑`).

Thank you !

**Comment by benrubson** [comment]
As we do not have so many news from the developper, I tried to correct this issue myself.
So for those who have to courage to recompile Telephone to have their proper patched version, here is a workaround.

In Classes/View and Controller/Account/AccountController.m, line 344, add :
```
[[aCallController window] setTitle:[NSString stringWithFormat:@"%@ → %@", _accountDescription,[[aCallController window] title]]];
```

Same file, line 788, modify with this :
```
NSString *finalTitle = [NSString stringWithFormat:@"%@ ← %@", _accountDescription, [[[aCall remoteURI] SIPAddress] componentsSeparatedByString:@"@"][0]];
```

**Comment by benrubson** [comment]
Alexei, could we think about this small enhancement in the 1.1.5 milestone please ?

Thank you very much !

Ben

**Comment by benrubson** [comment]
*// I just made some modification to work with Asterisk Originate function.*

Alexei, could we think about this small enhancement in the 1.1.5 milestone please ?

Thank you very much !

Ben

**Comment by eofster** [comment]
I don’t think this is gonna make it into 1.1.5. Only the absolute minimum of bug fixing changes should go into 1.1.5. However, this is likely to be fixed in the releases after that.

**Comment by benrubson** [comment]
Alexey, could we think about this feature request please (also see PR #184) ? :)
Many thanks 👍
