### ISSUE TITLE
Crash on XCode 6 / 10.10

### ISSUE THREAD

**Issue by robertoschwald** [eofster/Telephone#120]
Tried with XCode 6.1.1 and 6.2beta.

The following changes needed to be perfomed to make compilation work:
 - explicitely cast all [NSApp delegate] to [((AppController*)[NSApp delegate]) 

But when running, EXC_BAD_ACCESS code 2 happens in main.m

**Comment by bethrezen** [comment]
Have you found fix for EXC_BAD_ACCESS?

**Comment by bethrezen** [comment]
I've found the solution http://stackoverflow.com/questions/26727803/no-known-instance-method-error-nsstring-after-updating-xcode-osx
Switching to 10.9 sdk solves it. But the code still needs to be rewritten and I don't know how.

**Comment by thierryc** [comment]
Thank you ! 
The code still needs to be rewritten and I don't know how too !

**Comment by eofster** [comment]
Seems to be not relevant any more because it compiles in the latest Xcode 7.3.
