### ISSUE TITLE
Welcome and hold audio track

### ISSUE THREAD

**Issue by mungle** [eofster/Telephone#127]
I was wandering if is possible to have a welcome message/sound on incoming calls so when somebody call my number he can hear music or informations. This could be also great to have on "hold".
Thank you

**Comment by eofster** [comment]
Although it is technically possible, it is usually done on the server side. For example, a company sets up some telephony software like Asterisk on its server and this server software has features like greetings, voice menus, conferences, and music on hold.

**Comment by mungle** [comment]
I felt that was more server side, anyway it will be great to have also on software side as we have not any system like asterisk and we use only one phone number. We just desire a welcome message... hope you could add as new feature one day!

**Comment by mungle** [comment]
I was looking around trying to install freeswitch.org that seems do what I want to achieve but I'm having some troubles during installation... As I only need this feature, is it really impossible to add some freeswitch.org library in your app?

**Comment by eofster** [comment]
Technically it is possible to implement also with PJSIP - the library that Telephone already uses. However, this is a typical server-side feature that doesn’t fit into Telephone’s concept. Which is to be thin and minimalist softphone.
