### ISSUE TITLE
User agent can’t be started with DNS SRV and IPv6

### ISSUE THREAD

**Issue by eofster** [eofster/Telephone#150]
When DNS SRV is enabled and the computer has an IPv6 interface, SIP user agent can’t be started.

**Comment by lukehamburg** [comment]
Any ideas on how to fix this one? I have native IPv6 at home + work and this one is biting me.

**Comment by eofster** [comment]
I haven’t investigated this problem yet, but I plan to do so for the next release where I plan to add support for IPv6-only networks.

**Comment by eofster** [comment]
This has been fixed by updating PJSIP to the latest version 2.5.5 (#255).
