### ISSUE TITLE
Project file hard-codes build OS

### ISSUE THREAD

**Issue by nriley** [eofster/Telephone#163]
When I was troubleshooting the crash-on-launch issue (#162) I tried building Telephone on 10.11.2 instead of 10.10.5, but it failed to link because OS X 10.10.5's Darwin release was hard-coded in the OTHER_LDFLAGS (e.g. "-lpjsua-x86_64-apple-darwin14.5.0").  This is easy enough to fix, but ideally Telephone should be more friendly to building on multiple OS releases.

**Comment by robertoschwald** [comment]
+1

**Comment by robertoschwald** [comment]
I recommend to change the README:

    $ CFLAGS="-mmacosx-version-min=10.9" ./configure --target=x86_64-apple-darwin

and to remove all OS versions from the libraries in "Other Linker Flags".

This way, it is always compilable.

**Comment by eofster** [comment]
Do you know how to make PJSIP build process not generate library names with the current Darwin version? It always bugged me, but I never really dived into it.

Speaking about `-mmacosx-version-min=10.9` when configuring PJSIP, last time I tried omitting this, the result library crashed on the earlier OS X versions at some point.

**Comment by robertoschwald** [comment]
yes, thats exactly what --target does. it omits the os version from the lib name

**Comment by eofster** [comment]
Thanks a lot!
