### ISSUE TITLE
PRs ignored?

### ISSUE THREAD

**Issue by robertoschwald** [eofster/Telephone#164]
There are many PRs open since a long time which seem to be useful. As there are no comments on these PRs from the committers, may I ask why these useful PRs are not merged?

**Comment by eofster** [comment]
There are several reasons for that. The main are:

1. Some of them are not aligned with the plans for the future.
2. Some of them introduce features, for supporting which there are no resources (for example, localization pull requests).
3. I’d like to keep the number of project authors as small as possible to avoid potential legal complications in the future.

In general, people create pull requests without asking if they are needed. This by itself isn’t bad. On the contrary, it is a _very_ nice thing to do. But those requests often become not merged for the reasons above.

What I absolutely need to do is to communicate this more clearly to avoid any false expectations, and clean up the currently outdated pull requests.
