### ISSUE TITLE
Answer call from OS X notification

### ISSUE THREAD

**Issue by eofster** [eofster/Telephone#170]
It probably would be convenient to answer calls from system notifications.

**Comment by derhuerst** [comment]
:+1:

**Comment by Sija** [comment]
:+1:

**Comment by benrubson** [comment]
Yep, and if the call has already finished when we click on the notification, simply redial it (as if we would have clicked the "call back" / "redial" button in the call window).
Thank you 👍

**Comment by markdegrootnl** [comment]
+1
