### ISSUE TITLE
Is Telephone in active development?

### ISSUE THREAD

**Issue by jgrossi** [eofster/Telephone#171]
Hey guys!

I'm a Telephone user for 2 years and I think it's the best SIP client app for Mac. It's easy, fast and clean.

I saw the last release is from 2013 but the project here in Github is in active development, with commits from days ago.

Why not to release new versions? Maybe just here in Github to make it easy.

Thanks for this awesome app :-)

**Comment by eofster** [comment]
Hi and thank you for the kind words. I’ve been busy with some administrative stuff during the last couple of months, so the release has been postponed. But I’m planning to do it soon.

**Comment by jgrossi** [comment]
Thanks @eofster! I appreciate the support ;-)
