### ISSUE TITLE
SIP session timers

### ISSUE THREAD

**Issue by eofster** [eofster/Telephone#180]
In #51 @benrubson reports a problem with SIP session timers. Calls are terminated after exactly the same amount of time and increasing Asterisk’s `session-expires` parameter seems to help. Although PJSIP used in Telephone 1.1.4 supports session timers and should work out of the box, the calls are still terminated.

**Comment by eofster** [comment]
Here’s what’s happening in this specific case between Telephone 1.1.4 with PJSIP 2.4.5 and Asterisk 1.8.13.1:

1. Telephone declares session timers support.
2. In the INVITE Telephone doesn’t set the refresher role.
3. In 200 Asterisk sets the refresher role to UAS, making itself a refresher.
4. Asterisk sends the first re-INVITE and sets the refresher role to UAS again, assigning the role to Telephone, because in this dialog Asterisk is a UAC and Telephone is a UAS.
5. Both Telephone and asterisk try to refresh the session by sending re-INVITEs, which causes a conflict and the call is terminated by both ends.

The same configuration works fine with Asterisk 13.7.1. This version of Asterisk keeps the refresher role at Asterisk by specifying UAC as a refresher on step 4.

**Comment by eofster** [comment]
I’ve decided to deactivate SIP session timers support in Telephone, unless session timers are explicitly required by another party.

Being a softphone, a piece of software that is explicitly controlled by the user, it seems unnecessary to insist on session timers being enabled. Telephone should just correctly support them when and if they are required by another party.

**Comment by benrubson** [comment]
Thank you very much Alexey :+1: 

If ever SIP session timers are required by another party, an option in Telephone preferences should be nice :+1:

**Comment by eofster** [comment]
If SIP session timers are required by another party, it should just work out of the box with the current configuration.

**Comment by benrubson** [comment]
Ah yes Alexey, sorry for misunderstanding.
I wanted to say, "If ever SIP session timers are required by other people in Telephone itself, an option in Telephone preferences should be nice".
