### ISSUE TITLE
opus audio codec support

### ISSUE THREAD

**Issue by funkenstrahlen** [eofster/Telephone#233]
Have you thought about supporting the opus audio codec? A lot of end points start to support it and it provides amazing call quality.

**Comment by eofster** [comment]
You know, I recently came across it again, this time while listening to the Freak Show, and thought that I probably should add it too. PJSIP 2.5 seems to support it.

**Comment by eofster** [comment]
Added in #264

**Comment by funkenstrahlen** [comment]
Will you release a complete build with integrated opus support?

**Comment by eofster** [comment]
Yes. In fact, I’ve just submitted it for review.

**Comment by funkenstrahlen** [comment]
Great!

**Comment by eofster** [comment]
@funkenstrahlen It’s been finally approved by Apple and is available on Mac App Store.
