### ISSUE TITLE
Automatic (re)connection (reopens #117)

### ISSUE THREAD

**Issue by benrubson** [eofster/Telephone#235]
Hello,

This bug re-opens #117.
Telephone does not automatically connects (and re-connects), when used SIP port is not the default one.
So if you use mysipprov.net:1234 in `domain` field, Telephone does not automatically (re)connects.

Thank you !

Ben

**Comment by eofster** [comment]
#117 hasn’t been released yet. It’s part of the 1.2 release, but recently 1.1.7 hot fix has been released.

**Comment by benrubson** [comment]
Oops sorry Alexey, and thank you !
