### ISSUE TITLE
Relation to "phone.systems"?

### ISSUE THREAD

**Issue by asmod3us** [eofster/Telephone#244]
What is the relation of Telephone to https://phone.systems? It looks almost the same, but I wasn't able to find source code for it.

**Comment by eofster** [comment]
It's a clone of an old version ☹️ and this project has neither any influence nor relation to it.

**Comment by asmod3us** [comment]
Thanks for clarifying! Aren't they violating the GPL with this?

**Comment by eofster** [comment]
To my knowledge, one doesn't have to automatically publish the sources, but rather has to provide them upon request to the users of the compiled program. So, if you install the app you should have a right to ask them for the sources.

Also, Telephone's source code of that version was released under BSD license that doesn't have such restriction. However, the free version of PJSIP is under GPL, so if it was used when building that end product, GPL rules apply to the whole end product.

**Comment by asmod3us** [comment]
Interesting, and thanks for the background info. I've decided to stay away from their product :)
