### ISSUE TITLE
Auto change status when internet is active again

### ISSUE THREAD

**Issue by 1951FDG** [eofster/Telephone#272]
This is basically a feature request, if internet connection (WIFI, or screen lock, login screen) is lost, Telephone tends to go offline and you’ve got to manually put it back online again. Is there a way for Telephone to automatically turn on when an internet connection is active again. This could be a preference setting. Maybe I can help out with this, if you point me in the right direction.

**Comment by eofster** [comment]
This must have been fixed as part of #117, but haven’t been released yet, because it is in review by Apple.
