### ISSUE TITLE
Crash [@ pjmedia_aud_stream_destroy ] waking laptop from sleep

### ISSUE THREAD

**Issue by luser** [eofster/Telephone#32]
I opened my laptop to wake it from sleep, and Telephone crashed on me. Here's the crash report:
https://gist.github.com/1070777

This is Telephone 1.0.1 on OS X 10.6.7 running as a 64-bit app.

**Comment by hexerei** [comment]
Hi William, and hi Alexei :)

Certainly the issue still exists and i am encountering it around 3 to 4 times a week, so it is not an *always* occurring issue.

I am using *version 1.1.4 (114)* of *Telephone.app* and *OS X 10.11.1* on *Intel Core i7* **daily**

You may find my *crash report* here:
[telephone.app - crash on 10.11.1 after wake-up](https://gist.github.com/hexerei/fb7f4128f1beb2b87bed)

Ok, i am also one of those guys working late, getting tired and just slapping my lappy to sleep. But that is in reality such a wonderful feature. I remember my first laptop, it was delivered with *Windows for Workgroups 3.11“ - no other choice back then - and it had this feature to suspend the memory to disk (a procedure that took more than 12 seconds) - i already loved it in the 90’s (WfW actually worked with it) and it sure should be default in our time.

I know, suspending does not leave much time to freeze state, but hey it works at times, so there must be something tricky sticking around there.

If you need any help on this issue. I could give it a try - biding time :)

**Comment by eofster** [comment]
Does the problem still exist in version 1.2.4?
