### ISSUE TITLE
Registration being sent to Localhost

### ISSUE THREAD

**Issue by Enaku** [eofster/Telephone#33]
Hi, eofster,

Telephone is a great application, love your work!

I'm getting a very strange thing occurring where my registration requests appear to be sent from localhost (127.0.0.1). As a result, my PBX is telling me to go away. After closing and opening Telephone again, it seems to be working okay now. I'm not sure how to replicate the issue, but I do have a wired (Ethernet) and Wireless adapter - it's possible that they may be getting confused? Or possibly if my Mac has woken up from sleep/hibernation and Telephone is running, it may not have an interface up yet? See below for an excerpt from Telephone.log

== BEGIN LOG ==
 ```
--end msg--
 10:29:12.799   pjsua_core.c  TX 744 bytes Request msg REGISTER/cseq=55614 (tdta0x1010bc000) to UDP 172.23.4.2:5060:
REGISTER sip:172.23.4.2 SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:55947;rport;branch=z9hG4bKPj.8ZPEgpNgbf8VifaldVQJ53i2EXJkF0c
Max-Forwards: 70
From: "Kane Rogers" <sip:ext120@172.23.4.2>;tag=33DXsxio38k06ynp18D3iYLsuaEp1crJ
To: "Kane Rogers" <sip:ext120@172.23.4.2>
Call-ID: r2Qz4gSwytHJNeckBkqR7.iNBhJX6slV
CSeq: 55614 REGISTER
User-Agent: Telephone 1.0.2
Contact: "Kane Rogers" <sip:ext120@127.0.0.1:55947;ob>
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Authorization: Digest username="ext120", realm="voip.bluereef.com.au", nonce="aa37147fb1371db5673b491eaef8536c", uri="sip:172.23.4.2", response="5b0bbcb19fa1bdbd2e0b60a6596857b2", opaque="1314145751"
Content-Length:  0
 ```
 
--end msg--
 10:29:12.815   pjsua_core.c  RX 476 bytes Response msg 400/REGISTER/cseq=55614 (rdata0x10105de28) from UDP 172.23.4.2:5060:
SIP/2.0 400 Bad Request
Via: SIP/2.0/UDP 127.0.0.1:55947;rport=55947;received=172.23.10.46;branch=z9hG4bKPj.8ZPEgpNgbf8VifaldVQJ53i2EXJkF0c
To: "Kane Rogers" <sip:ext120@172.23.4.2>
From: "Kane Rogers" <sip:ext120@172.23.4.2>;tag=33DXsxio38k06ynp18D3iYLsuaEp1crJ
CSeq: 55614 REGISTER
Call-ID: r2Qz4gSwytHJNeckBkqR7.iNBhJX6slV
Server: Epygi Quadro SIP User Agent/v5.2.47 (QUADROM-IPPBX)
Warning: 399 epygi_quadro_sip_ua "Quadro Internal Rejection"
Content-Length: 0

== END LOG ==

**Comment by eofster** [comment]
I believe this should be fixed by now. Feel free to reopen this issue or open the new one, if it’s not.
