### ISSUE TITLE
Not responding to RTCP PINGs

### ISSUE THREAD

**Issue by fallenpegasus** [eofster/Telephone#51]
When on long calls into my corporate provided SIP PBX, the call hangs up after half an hour.  According to the administrator of our SIP servers, they send a RTCP PING every 5 minutes, and after not getting ping response after 6 tries, their gateway shuts the connection down.

So, please make Telephone.app respond to RTCP PINGs.

Thanks!

**Comment by benrubson** [comment]
Alexei, do you think you could handle SIP Session-Timers in the future release please ?
That's sometimes embarrassing to have the call cut during the conversation :|
Thank you very much !
Ben

**Comment by eofster** [comment]
The next bug fixing release, 1.1.5, should include the latest stable PJSIP release. I haven’t checked it for the feature in question yet, but if it is there and enabled by default, it should just work.

**Comment by benrubson** [comment]
I'm running one of your last commits with PJSIP 2.4.5 since a few days.
Unfortunately issue is still present, call hangs up after the Asterisk ``session-expires`` parameter.
Thank you Alexei :+1:

**Comment by eofster** [comment]
Okay, thank you for the info.

**Comment by eofster** [comment]
@fallenpegasus Mark, if you’re still here and interested, could you please ask the administrator to provide some more information about RTCP PINGs? What exactly is sent and what exactly is expected to be received? I couldn’t find the term “RTCP PING” in the RFC 3550. Could it be some custom configuration that is not described in the RFCs?

**Comment by benrubson** [comment]
@eofster, sounds like they are documented in RFC 4028 (SIP Session-Timers).
Sounds like PJSIP handles Session-Timers, perhaps you need to "activate" them ?

**Comment by eofster** [comment]
@benrubson Ben, let’s discuss the SIP session timers problem in #180.

**Comment by benrubson** [comment]
Don't you think these 2 issues are the same ?

**Comment by eofster** [comment]
They might be, but let’s separate them to avoid overlapped discussions.

**Comment by eofster** [comment]
> Sounds like PJSIP handles Session-Timers, perhaps you need to "activate" them ?
That’s exactly the strange part. SIP session timers seem to be activated in PJSIP by default. It itself sets the header when making calls.

**Comment by eofster** [comment]
In the originally reported problem calls hang up after 30 minutes. This seems very much like the default limit of SIP session timers, and not like a timer related to RTP, which usually depends on voice being transmitted. I suspect that the original problem could be incorrectly diagnosed and it might be fixed in #180.

Closing this issue for now, but if my suspicion is incorrect and the behavior stays the same after Telephone 1.1.5 is released, please reopen the issue.
