### ISSUE TITLE
Mute doesn't work

### ISSUE THREAD

**Issue by deviantintegral** [eofster/Telephone#60]
I press "M" to mute, and Telephone says I'm muted. But my voice is still transmitted! I can replicate this by opening a call, muting myself, and then listening to my name as recorded by the conference line. This makes Telephone unusable for me.

**Comment by eofster** [comment]
Does mute not work for you when you put a call on hold and then off hold? Or does it happen without using the hold feature? Just thinking if this issue and #118 are be the same.

**Comment by derhuerst** [comment]
> 1) are you using the mute menu (the 'm' key) to mute, or the mute hardware button on your headset?

`m` key.

> 2) do you see "mic muted" on the call window?

yes.

> 3) which version of Telephone, OSX?

Telephone: `1.1.4`
OS X: `10.9.5`

> 4) are you able to make an other test with an Echo test (of an Asterisk box for example, *43 by default in trixbox)?

No, I have no other box.

> 5) what is your audio setup? (OSX audio system preferences, Telephone audio preferences, headset)

- input via Logitech HD Pro C920 Webcam (USB)
- output via speakers connected to headphone jack (default output channel)
- "use only G.711-Codec" active

**Comment by hashar** [comment]
#118 has a patch suggestion ( https://github.com/eofster/Telephone/issues/118#issuecomment-107189194 ).  Maybe worth building an alpha release for test purposes?   I no more use telephone myself :-/

**Comment by eofster** [comment]
I think #118 is unrelated. I see the problem when a call is taken off hold. But it seems like people experience the muting problem even without call hold.

**Comment by eofster** [comment]
#181

**Comment by eofster** [comment]
Fixed in #181.
