### ISSUE TITLE
Cannot register after sleep

### ISSUE THREAD

**Issue by spokrandt** [eofster/Telephone#79]
After mac Air sleeps Telephone is unable to reregister with voip provider.   killing and restarting app the can register

**Comment by robertoschwald** [comment]
It is not fixed in 1.1.4 on Yosemite 10.10.2 here. 
Test:
 - Telephone is connected (available). 
- Send Computer to sleep
- wake up
- Telephone is disconnected (offline) and does not reconnect

**Comment by benrubson** [comment]
See #117 for a fix.

**Comment by suderman** [comment]
One workaround is use Keyboard Maestro (or anything else that watches sleep events) to quit Telephone on system sleep, and launch Telephone on system wake. This keeps my laptop connected throughout the day.
